spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: catalog-route
              uri: ${CATALOG_SERVICE_URL:http://catalog-service}
              predicates:
                - Path=/books/**
            - id: order-route
              uri: ${ORDER_SERVICE_URL:http://order-service}
              predicates:
                - Path=/orders/**
  data:
    redis:
      host: ${REDIS_HOST:polar-redis}