spring:
  r2dbc:
    url: r2dbc:postgresql://polar-postgres:5432/polardb_order
    username: user
    password: password
  flyway:
    url: jdbc:postgresql://polar-postgres:5432/polardb_order
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

polar:
  catalog-service-uri: "http://catalog-service"